services:
    breadcrumbs_bundle.catalog:
        class: Adamski\Symfony\BreadcrumbsBundle\Model\Catalog

    Adamski\Symfony\BreadcrumbsBundle\Model\Catalog:
        alias: breadcrumbs_bundle.catalog

    breadcrumbs_bundle.twig.extension.breadcrumbs:
        class: Adamski\Symfony\BreadcrumbsBundle\Twig\BreadcrumbsExtension
        arguments:
            - "@breadcrumbs_bundle.catalog"
        tags:
            - { name: twig.extension }
